name: Fetch & Analyze (Daily 22:10 TPE)

on:
  schedule:
    # 22:10 Asia/Taipei = 14:10 UTC
    - cron: "10 14 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 允許 commit 回 repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy

      - name: Run fetch & analyze
        run: |
          python fetch_analyze.py

      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          git commit -m "Update data: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
